### ISSUE TITLE
A suggestion + a question about how to scan a pod on demand.

### ISSUE THREAD

**Issue by Tom284** [mittwald/kube-av#11]
Hey, I would like to use kube-av for an internship project and I found a potential alteration for the readme. For the example I had to add a claimName so that it becomes this: 

```
apiVersion: av.mittwald.de/v1beta1
kind: VirusScan
metadata:
  name: example-virusscan
spec:
  # supported values: ["ClamAV"]
  engine: ClamAV

  # list of volumes to scan
  targets:

    # "volume" may be any kind of VolumeSource that you'd also use in
    # a PodSpec.
    - volume:
        persistentVolumeClaim:
            claimName: "claimName"
            path: my-pvc
        subPath: path/to/subdir  
```
Perhaps that could be an update for the readme?

For my question, I want to scan specific pods. How would I know the volume of a pod that I want to scan?
for example if my pod was created from this yaml file (from the official Kubernetes [docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/);
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
How would I know what volume to add so I can start an on demand scan?

Also would it be possible to create a scan on demand through the Kubernetes c# client using a version of this method [from the official c# client](https://github.com/kubernetes-client/csharp/blob/master/examples/yaml/Program.cs)?
